backend:
  name: github
  repo: taiguoqing-eng/myblog
  branch: main
  token: "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"
  #base_url: https://api.github.com # 明确指向 GitHub API
  
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布时间", name: "date", widget: "datetime" }
      - { label: "内容", name: "body", widget: "markdown" }