backend:
  name: github
  repo: taiguoqing-eng/myblog
  branch: main
  base_url: https://api.github.com # 必须匹配你 Vercel 绑定的域名
  auth_endpoint: login/oauth/authorize

media_folder: "static/images"        # 对应 static/images
public_folder: "/images"      # 访问路径

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 建议加上日期，避免路径冲突
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布时间", name: "date", widget: "datetime" }
      - { label: "分类", name: "categories", widget: "list", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "内容", name: "body", widget: "markdown" }